// Export utilities — PDF via jsPDF, CSV via plain string
import { jsPDF } from 'jspdf';

function fmtDate(iso) {
  return new Date(iso).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
}

function fmtAmt(n) {
  return 'Rs. ' + new Intl.NumberFormat('en-IN', { minimumFractionDigits: 2 }).format(n);
}

// ===== GROUP PDF =====
export function downloadGroupPDF(expenses, group, members) {
  const doc = new jsPDF({ format: 'a4', unit: 'mm' });
  const W = doc.internal.pageSize.getWidth();
  let y = 15;

  // Header
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('HostelPay', 15, y);
  y += 8;
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100);
  doc.text('Group Statement — ' + group.name, 15, y);
  y += 6;
  doc.text('Room Code: ' + group.room_code + '  |  Printed: ' + fmtDate(new Date().toISOString()), 15, y);
  y += 3;

  // Divider
  doc.setDrawColor(200);
  doc.line(15, y, W - 15, y);
  y += 8;

  // Table header
  doc.setFontSize(9);
  doc.setTextColor(80);
  doc.text('DATE', 15, y);
  doc.text('DESCRIPTION', 40, y);
  doc.text('PAID BY', 110, y);
  doc.text('AMOUNT', W - 15, y, { align: 'right' });
  y += 4;
  doc.setDrawColor(220);
  doc.line(15, y, W - 15, y);
  y += 5;

  // Rows
  doc.setFontSize(9);
  doc.setTextColor(30);
  let total = 0;
  expenses.forEach(e => {
    if (y > 270) { doc.addPage(); y = 15; }
    const payer = members.find(m => m.user_id === e.paid_by)?.user?.name || 'Unknown';
    doc.text(fmtDate(e.created_at), 15, y);
    doc.text(e.description.substring(0, 35), 40, y);
    doc.text(payer.substring(0, 18), 110, y);
    doc.text(fmtAmt(e.amount), W - 15, y, { align: 'right' });
    y += 6;
    total += e.amount;
    doc.setDrawColor(240);
    doc.line(15, y - 2, W - 15, y - 2);
  });

  // Total
  y += 4;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.text('TOTAL', 15, y);
  doc.text(fmtAmt(total), W - 15, y, { align: 'right' });

  // Footer
  y = doc.internal.pageSize.getHeight() - 10;
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.setFont('helvetica', 'normal');
  doc.text('Generated by HostelPay — Never forget who owes whom.', 15, y);

  doc.save(`HostelPay_${group.name.replace(/\s+/g, '_')}.pdf`);
}

// ===== GROUP CSV =====
export function downloadGroupCSV(expenses, group) {
  const rows = [
    ['Date', 'Description', 'Paid By', 'Amount (INR)'],
    ...expenses.map(e => [
      fmtDate(e.created_at),
      '"' + (e.description || '') + '"',
      e.payer?.name || e.paid_by,
      e.amount.toFixed(2),
    ]),
  ];
  const csv = rows.map(r => r.join(',')).join('\n');
  const blob = new Blob([csv], { type: 'text/csv' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `HostelPay_${group.name.replace(/\s+/g, '_')}.csv`;
  a.click();
  URL.revokeObjectURL(url);
}

// ===== PERSONAL PDF =====
export function downloadPersonalPDF(records, contact) {
  const doc = new jsPDF({ format: 'a4', unit: 'mm' });
  const W = doc.internal.pageSize.getWidth();
  let y = 15;

  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('HostelPay', 15, y);
  y += 8;
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100);
  doc.text('Personal Statement — ' + (contact?.name || 'Contact'), 15, y);
  y += 6;
  doc.text('Printed: ' + fmtDate(new Date().toISOString()), 15, y);
  y += 3;
  doc.setDrawColor(200);
  doc.line(15, y, W - 15, y);
  y += 8;

  doc.setFontSize(9);
  doc.setTextColor(80);
  doc.text('DATE', 15, y);
  doc.text('DESCRIPTION', 40, y);
  doc.text('TYPE', 110, y);
  doc.text('AMOUNT', W - 15, y, { align: 'right' });
  doc.text('STATUS', W - 40, y, { align: 'right' });
  y += 4;
  doc.setDrawColor(220);
  doc.line(15, y, W - 15, y);
  y += 5;

  doc.setFontSize(9);
  doc.setTextColor(30);
  records.forEach(r => {
    if (y > 270) { doc.addPage(); y = 15; }
    doc.text(fmtDate(r.created_at), 15, y);
    doc.text((r.description || '').substring(0, 35), 40, y);
    doc.text(r.type === 'lend' ? 'Lent' : 'Borrowed', 110, y);
    doc.text(fmtAmt(r.amount), W - 15, y, { align: 'right' });
    doc.text(r.status.toUpperCase(), W - 40, y, { align: 'right' });
    y += 6;
    doc.setDrawColor(240);
    doc.line(15, y - 2, W - 15, y - 2);
  });

  y = doc.internal.pageSize.getHeight() - 10;
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.setFont('helvetica', 'normal');
  doc.text('Generated by HostelPay — Never forget who owes whom.', 15, y);

  doc.save(`HostelPay_Personal_${(contact?.name || 'Contact').replace(/\s+/g, '_')}.pdf`);
}
